### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by AngeloModanez** [AngeloModanez/Task-List#2]
Requirements
- [x] Menu Sandwich -  Edit, Update, Done, Logout
- [x] Task - card: Tittle, CheckBox, Delete button, Edit button
- [x] New Task  button
- [x] Button Navigation - Login to TaskList
